language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: test
      script: npm run test:coveralls

    - stage: build docker image
      if: type = push AND branch = develop
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            git config credential.helper "store --file=.git/credentials"
            echo "https://$GITHUB_ACCESS_KEY:@github.com" > .git/credentials
            npm run release
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t jmeter-k8s .
            docker tag jmeter-k8s $DOCKER_USERNAME/jmeter-k8s:$(npm version | grep jmeter-k8s | grep -o "[0-9]\.[0-9]\.[0-9]")-develop
            docker push $DOCKER_USERNAME/jmeter-k8s:$(npm version | grep jmeter-k8s | grep -o "[0-9]\.[0-9]\.[0-9]")-develop
            git push origin HEAD:develop
            git push --tags
          fi

    - stage: build docker image
      if: branch = main
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t jmeter-k8s .
        - docker tag jmeter-k8s $DOCKER_USERNAME/jmeter-k8s:$(npm version | grep jmeter-k8s | grep -o "[0-9]\.[0-9]\.[0-9]")
        - docker tag jmeter-k8s $DOCKER_USERNAME/jmeter-k8s:latest
        - docker push $DOCKER_USERNAME/jmeter-k8s:$(npm version | grep jmeter-k8s | grep -o "[0-9]\.[0-9]\.[0-9]")
        - docker push $DOCKER_USERNAME/jmeter-k8s:latest
