---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-k8s-service-ext
  namespace: jmeter-k8s
spec:
  type: NodePort
  selector:
    app: jmeter-k8s
  ports:
  - port: 8081
    nodePort: 30002
    targetPort: connection
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-ext
  namespace: jmeter-k8s
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - port: 27018
    nodePort: 30001
    targetPort: connection