apiVersion: v1
kind: Namespace
metadata:
  name: jmeter-k8s
  labels:
    name: jmeter-k8s
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-main
  namespace: jmeter-k8s
  labels:
    role: jmeter-main
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassname:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  local:
    path: /mnt/jmeter-projects
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: pv-role
            operator: In
            values:
              - "jmeter-main"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-main
  namespace: jmeter-k8s
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: volume-main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-k8s-deployment
  namespace: jmeter-k8s
  labels:
    app: jmeter-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-k8s
  template:
    metadata:
      labels:
        app: jmeter-k8s
    spec:
      volumes:
        - name: volume-main
          persistentVolumeClaim:
            claimName: claim-main
      containers:
        - name: jmeter-k8s
          image: deividbatfish2/jmeter-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: connection
          env:
            - name: MONGO_URL
              value: mongodb://mongodb-service.jmeter-k8s:27017/jmeter-k8s
          resources:
            requests:
              cpu: 64m
              memory: 64M
            limits:
              cpu: 128m
              memory: 128M
          livenessProbe:
            httpGet:
              path: /api/health-check
              port: connection
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 1
          volumeMounts:
            - name: volume-main
              mountPath: /usr/app/data
